version: '3'

services:
  master:
    image: dockerhadoopcluster_master
    hostname: master
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
  slave1:
    image: dockerhadoopcluster_slave1
    ports:
      - "9901:9864"
      - "8041:8042"
  slave2:
    image: dockerhadoopcluster_slave2
    ports:
      - "9902:9864"
      - "8042:8042"

